server:
  port: 8090

logging:
  path: ./logs
  #level: info
  
spring:
  application:
    name: spring-boot-demo
  jpa:
    database: "MYSQL"
    show-sql: "true"
  datasource:
    platform: "mysql"
    url: "jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT"
    username: "root"
    password: "123456"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"

  mvc:
    view:
      prefix: /pages/
      suffix: .html
      
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fb.springbootdemo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    classpath*:mapper/*.xml
  type-aliases-package: com.fb.springbootdemo.entity
      
magic: null